version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce123
      POSTGRES_DB: ecommerce_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9092:9092"

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # tránh trùng với postgres chính

  user-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: user_db
    volumes:
      - user-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  product-db:
    image: postgres:15
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: product_db
    volumes:
      - product-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    volumes:
      - order-db-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_DB: payment_db
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  inventory-db:
    image: postgres:15
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  notification-db:
    image: postgres:15
    environment:
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_pass
      POSTGRES_DB: notification_db
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
  
  cart_db:
    image: postgres:15
    environment:
      POSTGRES_USER: cart_users
      POSTGRES_PASSWORD: cart_passs
      POSTGRES_DB: cart_dbs
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    ports:
      - "54422:5432"


volumes:
  postgres-data:
  redis-data:
  es-data:
  auth-db-data:
  user-db-data:
  product-db-data:
  order-db-data:
  payment-db-data:
  inventory-db-data:
  notification-db-data:
  cart-db-data:
