// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v3.20.3
// source: cart.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "cart";

export interface AddToCartRequest {
  userId: string;
  skuId: string;
  quantity: number;
  price: number;
  itemDetail: ItemDetail | undefined;
}

export interface ItemDetail {
  name: string;
  price: number;
  skuCode: string;
  stock: number;
  options: { [key: string]: string };
}

export interface ItemDetail_OptionsEntry {
  key: string;
  value: string;
}

export interface AddToCartResponse {
  message: string;
}

export interface GetCartRequest {
  userId: string;
}

export interface CartItem {
  productId: string;
  skuId: string;
  name: string;
  image: string;
  quantity: number;
  price: number;
  options: { [key: string]: string };
}

export interface CartItem_OptionsEntry {
  key: string;
  value: string;
}

export interface GetCartResponse {
  items: CartItem[];
}

export const CART_PACKAGE_NAME = "cart";

export interface CartServiceClient {
  addToCart(request: AddToCartRequest): Observable<AddToCartResponse>;

  getCart(request: GetCartRequest): Observable<GetCartResponse>;
}

export interface CartServiceController {
  addToCart(request: AddToCartRequest): Promise<AddToCartResponse> | Observable<AddToCartResponse> | AddToCartResponse;

  getCart(request: GetCartRequest): Promise<GetCartResponse> | Observable<GetCartResponse> | GetCartResponse;
}

export function CartServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addToCart", "getCart"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CART_SERVICE_NAME = "CartService";
