// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v3.20.3
// source: inventory.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "inventory";

export interface CheckStockRequest {
  skuCodes: string[];
}

export interface StockItem {
  skuCode: string;
  stock: number;
}

export interface CheckStockResponse {
  items: StockItem[];
}

export interface ReserveStockRequest {
  items: ReserveStockItem[];
}

export interface ReserveStockItem {
  skuCode: string;
  quantity: number;
}

export interface ReserveStockResponse {
  success: boolean;
  reservedSkuCodes: string[];
}

export interface SyncStockFromRedisRequest {
  skuCodes: string[];
}

export interface SyncStockFromRedisResponse {
  success: boolean;
  syncedSkuCodes: string[];
}

export const INVENTORY_PACKAGE_NAME = "inventory";

export interface InventoryServiceClient {
  checkStock(request: CheckStockRequest): Observable<CheckStockResponse>;

  reserveStock(request: ReserveStockRequest): Observable<ReserveStockResponse>;

  syncStockFromRedis(request: SyncStockFromRedisRequest): Observable<SyncStockFromRedisResponse>;
}

export interface InventoryServiceController {
  checkStock(
    request: CheckStockRequest,
  ): Promise<CheckStockResponse> | Observable<CheckStockResponse> | CheckStockResponse;

  reserveStock(
    request: ReserveStockRequest,
  ): Promise<ReserveStockResponse> | Observable<ReserveStockResponse> | ReserveStockResponse;

  syncStockFromRedis(
    request: SyncStockFromRedisRequest,
  ): Promise<SyncStockFromRedisResponse> | Observable<SyncStockFromRedisResponse> | SyncStockFromRedisResponse;
}

export function InventoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkStock", "reserveStock", "syncStockFromRedis"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InventoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InventoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INVENTORY_SERVICE_NAME = "InventoryService";
