export enum AuditAction {
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  ASSIGN_ROLE = 'ASSIGN_ROLE',
  REMOVE_ROLE = 'REMOVE_ROLE',
  ASSIGN_PERMISSION = 'ASSIGN_PERMISSION',
  REMOVE_PERMISSION = 'REMOVE_PERMISSION',
}
